

Level:
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, $1a, $1b, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, $1a, $1b, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, uuu, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, uuu, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, uuu, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, $1a, $1b, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, uuu, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, uuu, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, uuu, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, $1a, $1b, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
  db ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, ooo, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, BBB, 
LevelEnd:



DEF levelHeight EQU $12
DEF levelWidth EQU ((LevelEnd-Level)/levelHeight)